{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntestcases\\test_demo.py:29: Exception"}, "start": 1663577779057, "stop": 1663577779057, "uuid": "f6e994c4-5fbc-4e5d-b2a7-1061d5d1c27a", "historyId": "5d4ff0041020ffe02bf23745526c8de0", "testCaseId": "72c659b5f8f4de40fb5043fdcd5739d7", "fullName": "testcases.test_demo#test_broken", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_demo"}, {"name": "host", "value": "SHANB-057776"}, {"name": "thread", "value": "19300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_demo"}]}